Importing Data
np.loadtxt () is a NumPy function used to load data from a text file (like .txt or .csv) into a NumPy array.
It expects numerical data (numbers only) by default

In [26]:
# Import NumPy using its standard alias, np
import numpy as np 

# Create any array from a .txt file

"""
1 2 3
4 5 6
7 8 9
"""
# Only Numeric data
txt = np.loadtxt('PersonNumeric.txt') 
print(txt)

print()

"""
John 25 72.5
Alice 30 68.0
"""
# This will read all values as strings.
txt = np.loadtxt('PersonString.txt', dtype=str) 
print(txt)

print()
"""
Name Age Height
John 25 72.5
Alice 30 68.0
"""
# If the file has a header (column names)
txt = np.loadtxt('PersonStringHeader.txt', dtype=str, skiprows=1)
print(txt)

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]

[['John' '25' '72.5']
 ['Alice' '30' '68.0']]

[['John' '25' '72.5']
 ['Alice' '30' '68.0']]


If your file mixes text and numbers (like names and ages), np.genfromtxt() is more flexible:
Name Age Height
John 25 72.5
Alice 30 68.0

In [32]:
txt = np.genfromtxt('Person.txt', dtype=str, delimiter=',')
print(txt)

['Name Age Height' 'John 25 72.5' 'Alice 30 68.0']


Skipping the header

In [31]:
txt = np.genfromtxt('Person.txt', dtype=str, delimiter=',', skip_header=1)
print(txt)

['John 25 72.5' 'Alice 30 68.0']


If the file is comma-separated (CSV format)

Name,Age,Amount
John,25,72.5
Alice,30,68.0
Silent,30,68.0
Noise,30,68.0

In [27]:
# Create any array from a .csv file
csv = np.genfromtxt('Person.csv', delimiter=',', dtype=str)
print(csv)


[['"Name' 'Age' 'Amount"']
 ['"John' '25' '72.5"']
 ['"Alice' '30' '68.0"']
 ['"Silent' '30' '68.0"']
 ['"Noise' '30' '68.0"']]


In [37]:
#arr = np.array([[1, 2, 3],
#                [4, 5, 6],
#               [7, 8, 9]])

arr = np.array([[1.0, 2.0, 3.0],
                [4.0, 5.0, 6.0],
                [7.0, 8.0, 9.0]])

np.savetxt('Person1.txt', arr, delimiter='')

#Writes an array to a .txt file
#np.savetxt('Person.txt' , arr, delimiter='' )